'use client'

import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { Card } from '@/components/ui/card'
import Image from 'next/image'
import {
  CheckCircle,
  Truck,
  FileCheck,
  Shield,
  Trash2,
  BookOpen,
  Lock,
} from 'lucide-react'
import { ClientsCarousel } from '@/components/clients-section'

const services = [
  {
    icon: Shield,
    title: 'Compliance Management',
  },
  {
    icon: Truck,
    title: 'Waste Pick-up',
  },
  {
    icon: Lock,
    title: 'Data Destruction',
  },
  {
    icon: Trash2,
    title: 'Annual Return Filing',
  },
  {
    icon: CheckCircle,
    title: 'Creating a Change',
  },
]

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2,
    },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6 },
  },
}

export default function ConsumerPage() {
  return (
    <main className="min-h-screen bg-background">

      <section className="relative py-28 lg:py-40 overflow-hidden md:min-h-[calc(100vh-80px)]">
        {/* Banner Image */}
        <Image
          src="/consumer_banner.jpeg"
          alt="Our Services Banner"
          fill
          priority
          className="w-full h-full object-fill object-center"
        />
        {/* Dark Overlay */}
        <div className="absolute inset-0 bg-black/60" />
        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <h1 className="text-4xl lg:text-5xl font-bold mb-6 text-white">
              We bring <span className='text-primary'>Zero-Waste Economy</span>
              <span className="block font-bold">accessible for everyone</span>
            </h1>
            <p className="text-lg text-white mb-8">
              By 2030, global E-Waste generation is projected to reach approximately 82 million
              tonnes. Join with us for making recycling a habit of living.
            </p>
          </motion.div>
        </div>
      </section>


      {/* Bulk Consumer Section */}
      <section className="pt-12 lg:pt-20">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
            >
              <h2 className="text-3xl lg:text-4xl font-bold text-foreground pb-4">
                Bulk Consumer
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                Maximum Quantity of waste in India is generated by bulk consumers such as corporates, institutions and government bodies. Managing this waste responsibly is not just a necessity, but a legal and environmental responsibility.
              </p><br />
              <p className="text-muted-foreground leading-relaxed">
                At Shiv Shakti Metals, we provide end-to-end waste management solutions tailored for bulk consumers. Whether you are a startup, corporate, hotels, hospitals, educational institutions, or government organizations — we ensure safe, compliant, and sustainable disposal of your waste.
              </p><br />
              <p className="text-muted-foreground leading-relaxed">
                At <strong>Shiv Shakti Metals</strong>, we specialize in handling a wide range of waste categories with complete safety, compliance and environmental responsibility, ensuring environmentally sound recycling practices in line with guidelines set by the Central Pollution Control Board (CPCB). As a CPCB-authorized and EPR-registered recycler, we also support Producers, Importers, and Brand Owners in fulfilling their Extended Producer Responsibility (EPR) obligations efficiently and transparently & we also provide EPR credit certificates to Producers, Importers, & Brand Owners.
              </p>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
              className="relative h-96 rounded-lg overflow-hidden"
            >
              <Image
                src="/consumer-section.jpeg"
                alt="Recycling facility"
                fill
                className="object-cover"
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* Clients Section */}
      <section className='py-15 bg-muted/30 mt-12'>
        <ClientsCarousel />
      </section>
    </main>
  )
}
