'use client'

import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { Card } from '@/components/ui/card'
import Image from 'next/image'
import {
  CheckCircle,
  Truck,
  FileCheck,
  Shield,
  Trash2,
  BookOpen,
  Lock,
} from 'lucide-react'
import { ClientsCarousel } from '@/components/clients-section'

const services = [
  {
    icon: Shield,
    title: 'Compliance Management',
  },
  {
    icon: Truck,
    title: 'Waste Pick-up',
  },
  {
    icon: Lock,
    title: 'Data Destruction',
  },
  {
    icon: Trash2,
    title: 'Annual Return Filing',
  },
  {
    icon: CheckCircle,
    title: 'Creating a Change',
  },
]

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2,
    },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6 },
  },
}

const processCards = [
  {
    title: 'What We Offer',
    points: [
      'Compliance Management',
      'Doorstep Waste Pick-up',
      'Secure Data Destruction',
      'Annual Return Filing Support',
      'Sustainable Recycling Practices',
    ],
  },
  {
    title: 'Why Bulk Consumer Choose Shiv Shakti Metals?',
    points: [
      'Authorized & compliant recycler',
      'Transparent processes & proper documentation',
      'Quick response & efficient logistics',
      'Environment-friendly practices',
      'Trusted by multiple industries',
    ],
  },
  {
    title: 'Who Can Benefit?',
    points: [
      'Corporates & Offices',
      'IT Companies',
      'Hotels & Hospitality',
      'Hospitals',
      'Colleges & Universities',
      'Government Organizations',
      'Manufacturing Units',
    ],
  },
  {
    title: 'Why Choose Us for Medical Equipment Disposal?',
    points: [
      'Expertise in handling sensitive healthcare equipment',
      'Compliance with government and pollution control norms',
      'Data security for digital medical devices',
      'Eco-friendly recycling practices',
    ],
  },
]

export default function ConsumerPage() {
  return (
    <main className="min-h-screen bg-background">

      <section className="relative py-28 lg:py-40 overflow-hidden md:min-h-[calc(100vh-80px)]">
        {/* Banner Image */}
        <Image
          src="/consumer_banner.jpeg"
          alt="Our Services Banner"
          fill
          priority
          className="w-full h-full object-fill object-center"
        />
        {/* Dark Overlay */}
        <div className="absolute inset-0 bg-black/60" />
        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto"
          >
            <h1 className="text-4xl lg:text-5xl font-bold mb-6 text-white">
              We bring <span className='text-primary'>Zero-Waste Economy</span>
              <span className="block font-bold">accessible for everyone</span>
            </h1>
            <p className="text-lg text-white mb-8">
              By 2030, global E-Waste generation is projected to reach approximately 82 million
              tonnes. Join with us for making recycling a habit of living.
            </p>
          </motion.div>
        </div>
      </section>


      {/* Bulk Consumer Section */}
      <section className="pt-12 lg:pt-20">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
            >
              <h2 className="text-3xl lg:text-4xl font-bold text-foreground pb-4">
                Bulk Consumer
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                Maximum Quantity of waste in India is generated by bulk consumers such as corporates, institutions and government bodies. Managing this waste responsibly is not just a necessity, but a legal and environmental responsibility.
              </p><br />
              <p className="text-muted-foreground leading-relaxed">
                At Shiv Shakti Metals, we provide end-to-end waste management solutions tailored for bulk consumers. Whether you are a startup, corporate, hotels, hospitals, educational institutions, or government organizations — we ensure safe, compliant, and sustainable disposal of your waste.
              </p><br />
              <p className="text-muted-foreground leading-relaxed">
                At <strong>Shiv Shakti Metals</strong>, we specialize in handling a wide range of waste categories with complete safety, compliance and environmental responsibility, ensuring environmentally sound recycling practices in line with guidelines set by the Central Pollution Control Board (CPCB). As a CPCB-authorized and EPR-registered recycler, we also support Producers, Importers, and Brand Owners in fulfilling their Extended Producer Responsibility (EPR) obligations efficiently and transparently & we also provide EPR credit certificates to Producers, Importers, & Brand Owners.
              </p>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8 }}
              viewport={{ once: true }}
              className="relative h-96 rounded-lg overflow-hidden"
            >
              <Image
                src="/consumer-section.jpeg"
                alt="Recycling facility"
                fill
                className="object-cover"
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* Our Process Section */}
      <section className="py-12 lg:py-20">
        <div className="container mx-auto px-4">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={containerVariants}
            className="space-y-10"
          >
            <motion.div variants={itemVariants} className="text-center max-w-3xl mx-auto">
              <h2 className="text-3xl lg:text-4xl font-bold text-foreground">Our Process</h2>
            </motion.div>

            <motion.div
              variants={itemVariants}
              className="relative overflow-hidden rounded-3xl min-h-[260px] lg:min-h-[380px] shadow-lg"
            >
              <Image
                src="/our_process.jpeg"
                alt="Our process"
                fill
                className="object-cover"
              />
            </motion.div>

            <motion.div
              variants={containerVariants}
              className="grid gap-6 lg:grid-cols-2"
            >
              {processCards.map((card) => (
                <motion.div key={card.title} variants={itemVariants}>
                  <Card className="h-full border-border/60 bg-card/80 backdrop-blur-sm p-6 shadow-sm">
                    <h3 className="text-xl font-semibold text-foreground">{card.title}</h3>
                    <ul className="mt-4 space-y-3 text-muted-foreground">
                      {card.points.map((point) => (
                        <li key={point} className="flex items-start gap-3">
                          <span className="mt-2 h-2 w-2 rounded-full bg-primary shrink-0" />
                          <span>{point}</span>
                        </li>
                      ))}
                    </ul>
                  </Card>
                </motion.div>
              ))}
            </motion.div>

            <motion.div variants={itemVariants}>
              <Card className="border-primary/20 bg-primary/5 p-6 lg:p-8">
                <h3 className="text-2xl font-semibold text-foreground">Make a Responsible Choice</h3>
                <p className="mt-4 text-muted-foreground leading-relaxed">
                  Proper waste management is not just about disposal — it is about responsibility
                  towards the environment and future generations.
                </p>
                <p className="mt-4 text-muted-foreground leading-relaxed">
                  Partner with Shiv Shakti Metals and take a step towards sustainable waste
                  management.
                </p>
                <div className="mt-6">
                  <Button asChild size="lg">
                    <Link href="/contact-us">Schedule your pickup today</Link>
                  </Button>
                </div>
              </Card>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Clients Section */}
      <section className='py-15 bg-muted/30 mt-12'>
        <ClientsCarousel />
      </section>
    </main>
  )
}
